### ISSUE TITLE
Draw widget drop-down indicators

### ISSUE THREAD

**Issue by naglepuff** [DigitalSlideArchive/HistomicsUI#215]
There is some unexpected behavior in the draw widget if I click on any of the drop-downs for annotation types. For example, if I click on the drop-down arrow to change the options for drawing rectangle elements, the arrows for Ellipse, Brush, and the Draw Widget itself also flip.

**Comment by manthey** [comment]
Hmm... I thought this was fixed in the latest (but it might require that you are on the latest slicer_cli_web plugin, too).

**Comment by naglepuff** [comment]
I'll make sure I upgrade to the latest and verify if I'm still seeing this.

**Comment by manthey** [comment]
I believe this to be fixed.  I'll close the.  Please reopen if it is still a problem.
